name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"
  DOTNET_NOLOGO: "true"
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.fsproj', '**/paket.lock') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm install
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - run: npm test
        if: runner.os != 'Linux'

  pack:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm run pack
      - users: actions/upload-artifact@v1
        with:
          name: package.vsix
          path: ./*.vsix
